import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8f3e6',
  },
  shellScreen: {
    flex: 1,
    padding: 16,
    gap: 14,
  },
  content: {
    padding: 16,
    paddingBottom: 56,
    gap: 14,
  },
  chatContent: {
    paddingBottom: 56,
    gap: 10,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  hero: {
    paddingTop: 10,
    gap: 10,
  },
  heroTopRow: {
    paddingTop: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  heroTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  headerBackButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2f7254',
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBackButtonText: {
    color: '#2f7254',
    fontSize: 13,
    fontWeight: '700',
  },
  stepRail: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  stepRailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#ecf4ec',
  },
  stepRailItemDone: {
    backgroundColor: '#e3f2ea',
  },
  stepRailItemCurrent: {
    backgroundColor: '#2f7254',
  },
  stepRailNumber: {
    color: '#61746a',
    fontSize: 12,
    fontWeight: '800',
  },
  stepRailNumberActive: {
    color: '#ffffff',
  },
  stepRailLabel: {
    color: '#61746a',
    fontSize: 12,
    fontWeight: '700',
  },
  stepRailLabelActive: {
    color: '#ffffff',
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    color: '#4f6b5e',
    fontWeight: '700',
  },
  authLogo: {
    fontSize: 42,
    lineHeight: 48,
    color: '#2f7254',
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    color: '#2f7254',
    fontWeight: '800',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#2f7254',
  },
  shellTabBar: {
    flexDirection: 'row',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2f7254',
    backgroundColor: '#e9f4ee',
    overflow: 'hidden',
    position: 'relative',
  },
  shellTabSlider: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#2f7254',
  },
  shellTab: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRightWidth: 0,
    zIndex: 1,
  },
  shellTabLast: {
    borderRightWidth: 0,
  },
  shellTabActive: {
    backgroundColor: '#2f7254',
  },
  shellTabLabel: {
    color: '#2f7254',
    fontSize: 14,
    fontWeight: '800',
  },
  shellTabLabelActive: {
    color: '#ffffff',
  },
  scopeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  authModeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  scopePill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#edf1ef',
    borderWidth: 1,
    borderColor: '#d7dfda',
  },
  scopePillActive: {
    backgroundColor: '#2f7254',
    borderColor: '#2f7254',
  },
  scopePillLabel: {
    color: '#2f7254',
    fontSize: 13,
    fontWeight: '700',
  },
  scopePillLabelActive: {
    color: '#ffffff',
  },
  card: {
    backgroundColor: '#fffdf7',
    borderRadius: 24,
    padding: 20,
    gap: 14,
    shadowColor: '#2f7254',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  settingsCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#95b8a6',
    backgroundColor: '#fffef9',
    padding: 14,
    gap: 12,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#2f7254',
  },
  cardCopy: {
    fontSize: 16,
    lineHeight: 24,
    color: '#2f7254',
  },
  libraryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  librarySectionCard: {
    width: '48%',
    minWidth: 140,
    flexGrow: 1,
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#edf5ef',
    borderWidth: 1,
    borderColor: '#d7e2db',
    gap: 8,
  },
  librarySectionTitle: {
    color: '#2f7254',
    fontSize: 16,
    fontWeight: '800',
  },
  librarySectionCopy: {
    color: '#5a6b62',
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#cad8cf',
    backgroundColor: '#fffefb',
    paddingHorizontal: 14,
    paddingVertical: 15,
    fontSize: 17,
    color: '#2f7254',
    minHeight: 52,
  },
  textArea: {
    minHeight: 110,
    textAlignVertical: 'top',
  },
  primaryButton: {
    borderRadius: 18,
    backgroundColor: '#3f7d5f',
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 54,
  },
  primaryButtonSmall: {
    borderRadius: 16,
    backgroundColor: '#3f7d5f',
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
  secondaryButton: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#c7d6cc',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
    backgroundColor: '#f6f0df',
  },
  secondaryButtonSmall: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#c7d6cc',
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    backgroundColor: '#f6f0df',
  },
  secondaryButtonText: {
    color: '#2f7254',
    fontWeight: '700',
    fontSize: 16,
  },
  inlineActions: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  errorText: {
    color: '#9f2a26',
    lineHeight: 20,
    fontSize: 14,
  },
  noticeText: {
    color: '#2f7254',
    lineHeight: 20,
    fontSize: 14,
    fontWeight: '700',
  },
  loadingText: {
    color: '#2f7254',
    fontSize: 16,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loadingInline: {
    color: '#2f7254',
    fontSize: 14,
  },
  claimPreview: {
    backgroundColor: '#eef5ef',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  claimPreviewLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.3,
    color: '#638070',
    fontWeight: '700',
  },
  claimPreviewValue: {
    fontSize: 16,
    color: '#2f7254',
    fontWeight: '700',
  },
  stepSummary: {
    backgroundColor: '#eef5ef',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  stepSummaryTitle: {
    color: '#2f7254',
    fontSize: 17,
    fontWeight: '800',
  },
  stepSummaryCopy: {
    color: '#556860',
    fontSize: 14,
    lineHeight: 20,
  },
  deviceRowCard: {
    borderRadius: 18,
    backgroundColor: '#f8f4ea',
    borderWidth: 1,
    borderColor: '#d6dfd9',
    padding: 14,
    gap: 8,
  },
  deviceRowHeadline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  chatInboxHeader: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#f7f9f7',
    padding: 14,
    gap: 14,
  },
  chatInboxHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  chatInboxHeaderBody: {
    flex: 1,
    gap: 6,
  },
  chatInboxHeaderTitle: {
    color: '#2f7254',
    fontSize: 20,
    fontWeight: '800',
  },
  chatInboxHeaderCopy: {
    color: '#556860',
    fontSize: 14,
    lineHeight: 20,
  },
  chatInboxStatusCopy: {
    color: '#6b7f73',
    fontSize: 12,
    lineHeight: 18,
  },
  chatInboxSpaceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chatInboxSpaceChip: {
    minWidth: 150,
    flexGrow: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  chatInboxSpaceChipActive: {
    backgroundColor: '#2f7254',
    borderColor: '#2f7254',
  },
  chatInboxSpaceChipLabel: {
    color: '#2f7254',
    fontSize: 15,
    fontWeight: '800',
  },
  chatInboxSpaceChipLabelActive: {
    color: '#ffffff',
  },
  chatInboxSpaceChipMeta: {
    color: '#61746a',
    fontSize: 12,
    lineHeight: 18,
  },
  chatInboxSpaceChipMetaActive: {
    color: 'rgba(255,255,255,0.82)',
  },
  chatSessionRow: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#fff',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  chatSessionRowActive: {
    backgroundColor: '#eef5ef',
    borderColor: '#c4ded1',
  },
  chatSessionRowExplorer: {
    borderRadius: 12,
  },
  chatSessionRowContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    zIndex: 1,
  },
  chatSessionPressOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 12,
    backgroundColor: '#d8e9de',
    zIndex: 0,
  },
  chatSessionSwipeContainer: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
  },
  chatSessionSwipeFront: {
    zIndex: 2,
  },
  chatSessionDeleteAction: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 78,
    borderRadius: 12,
    backgroundColor: '#c53a36',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  chatSessionDeleteIcon: {
    color: '#ffffff',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '700',
  },
  chatSessionAvatarRail: {
    width: 44,
    alignItems: 'center',
    paddingTop: 2,
  },
  chatSessionAvatarBubble: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSessionAvatarBubbleGroup: {
    backgroundColor: '#2f7254',
  },
  chatSessionAvatarBubbleShared: {
    backgroundColor: '#eef5ef',
  },
  chatSessionAvatarBubblePrivate: {
    backgroundColor: '#fff1cf',
  },
  chatSessionAvatarLabel: {
    color: '#2f7254',
    fontSize: 16,
    fontWeight: '800',
  },
  chatSessionAvatarLabelOnDark: {
    color: '#ffffff',
  },
  chatSessionBody: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  chatSessionTitle: {
    color: '#2f7254',
    fontSize: 16,
    fontWeight: '800',
  },
  chatSessionTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  chatSessionMeta: {
    alignItems: 'flex-end',
    gap: 8,
  },
  chatSessionTimestamp: {
    color: '#61746a',
    fontSize: 12,
    fontWeight: '600',
  },
  chatSessionPreview: {
    color: '#556860',
    fontSize: 14,
    lineHeight: 20,
    flex: 1,
  },
  chatDetailHeader: {
    gap: 12,
    marginBottom: 12,
  },
  chatDetailHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  chatDetailHeaderBody: {
    gap: 6,
  },
  chatDetailTitle: {
    color: '#2f7254',
    fontSize: 22,
    fontWeight: '800',
  },
  chatDetailSubtitle: {
    color: '#556860',
    fontSize: 14,
    lineHeight: 21,
  },
  chatDetailParticipants: {
    color: '#4f6b5e',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  chatMessageGroup: {
    gap: 6,
    maxWidth: '88%',
    marginBottom: 8,
  },
  chatMessageGroupUser: {
    alignSelf: 'flex-end',
  },
  chatMessageGroupAssistant: {
    alignSelf: 'flex-start',
  },
  chatStatusNotice: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#f7f9f7',
    padding: 14,
    gap: 8,
    marginBottom: 10,
  },
  chatStatusNoticeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  chatStatusNoticeCopy: {
    color: '#2f7254',
    fontSize: 14,
    lineHeight: 20,
  },
  chatStatusTimestamp: {
    color: '#61746a',
    fontSize: 12,
    fontWeight: '600',
  },
  chatExplorerRail: {
    gap: 10,
    paddingHorizontal: 0,
  },
  chatTreeFolder: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#95b8a6',
    backgroundColor: '#fffef9',
    overflow: 'hidden',
  },
  chatTreeFolderActive: {
    borderColor: '#95b8a6',
  },
  chatTreeFolderHeader: {
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  chatTreeFolderHeaderBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  chatTreeFolderHeaderActions: {
    alignItems: 'flex-end',
    gap: 8,
  },
  chatTreeFolderTitle: {
    color: '#2f7254',
    fontSize: 16,
    fontWeight: '800',
  },
  chatTreeFolderMeta: {
    color: '#5d7266',
    fontSize: 13,
    lineHeight: 18,
  },
  chatTreeFolderChevron: {
    color: '#95b8a6',
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '800',
    minWidth: 24,
    textAlign: 'center',
  },
  spaceListCardRightRail: {
    alignItems: 'flex-end',
    gap: 8,
  },
  spaceTemplateBadge: {
    color: '#ffffff',
    backgroundColor: '#2f7254',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '800',
  },
  chatTreeFolderBody: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 10,
  },
  chatQuickStartButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#95b8a6',
    backgroundColor: '#fffef9',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chatQuickStartButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatQuickStartButtonText: {
    color: '#2f7254',
    fontSize: 12,
    fontWeight: '800',
  },
  chatQuickStartButtonChevron: {
    color: '#95b8a6',
    fontSize: 17,
    lineHeight: 17,
    fontWeight: '800',
  },
  chatQuickStartPopover: {
    marginTop: 8,
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#95b8a6',
    backgroundColor: '#fffef9',
    padding: 10,
    gap: 8,
  },
  chatQuickStartPopoverTitle: {
    color: '#2f7254',
    fontSize: 13,
    fontWeight: '800',
  },
  chatQuickStartRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#ffffff',
    padding: 10,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  chatQuickStartRowBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  chatQuickStartRowTitle: {
    color: '#2f7254',
    fontSize: 14,
    fontWeight: '800',
  },
  chatQuickStartRowCopy: {
    color: '#5d7266',
    fontSize: 12,
    lineHeight: 17,
  },
  chatTreeAppList: {
    marginTop: 4,
    gap: 10,
  },
  chatTreeSectionDivider: {
    height: 1,
    backgroundColor: '#dfe8e2',
    marginTop: 4,
    marginBottom: 6,
  },
  chatTreeSectionDividerCompact: {
    height: 1,
    backgroundColor: '#dfe8e2',
    marginTop: 0,
    marginBottom: 2,
  },
  chatTreeAppListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 2,
  },
  chatTreeAppListToggle: {
    color: '#95b8a6',
    fontSize: 20,
    lineHeight: 20,
    fontWeight: '800',
    minWidth: 22,
    textAlign: 'center',
  },
  chatAppCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#fffdf7',
    padding: 12,
    gap: 8,
  },
  chatAppHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  chatAppTitle: {
    color: '#2f7254',
    fontSize: 15,
    fontWeight: '800',
    flex: 1,
    minWidth: 0,
  },
  chatAppCopy: {
    color: '#56695e',
    fontSize: 14,
    lineHeight: 20,
  },
  chatEmptyStateCopy: {
    color: '#2f7254',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  chatScopeNavRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
    width: '100%',
  },
  chatScopeNavTabs: {
    flex: 1,
    flexDirection: 'row',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2f7254',
    backgroundColor: '#e9f4ee',
    overflow: 'hidden',
    position: 'relative',
  },
  chatScopeNavSlider: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#2f7254',
  },
  chatScopeNavTab: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRightWidth: 0,
    zIndex: 1,
  },
  chatScopeNavTabLast: {
    borderRightWidth: 0,
  },
  chatScopeNavTabActive: {
    backgroundColor: '#2f7254',
  },
  chatScopeNavTabLabel: {
    color: '#2f7254',
    fontSize: 14,
    fontWeight: '800',
  },
  chatScopeNavTabLabelActive: {
    color: '#ffffff',
  },
  chatScopeRefreshButton: {
    minWidth: 42,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2f7254',
    backgroundColor: '#2f7254',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  chatScopeRefreshIcon: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 20,
  },
  chatTreeEmbeddedPanel: {
    gap: 12,
  },
  statusTagOnline: {
    color: '#2f7254',
    backgroundColor: '#e8f5ee',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '700',
  },
  statusTagOffline: {
    color: '#7b4630',
    backgroundColor: '#f8e7df',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '700',
  },
  chatBubble: {
    borderRadius: 20,
    padding: 14,
    gap: 8,
  },
  chatBubbleMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  chatBubbleUser: {
    backgroundColor: '#2f7254',
  },
  chatBubbleAssistant: {
    backgroundColor: '#eef5ef',
  },
  chatBubblePending: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#b9c8c0',
    opacity: 0.92,
  },
  chatBubbleCopy: {
    color: '#2f7254',
    fontSize: 15,
    lineHeight: 22,
  },
  chatBubbleCopyUser: {
    color: '#ffffff',
  },
  chatBubbleCopyPending: {
    color: '#4f6b5e',
  },
  chatBubbleTimestamp: {
    color: '#61746a',
    fontSize: 12,
    fontWeight: '600',
  },
  chatBubbleTimestampUser: {
    color: 'rgba(255,255,255,0.8)',
  },
  groupParticipantPill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d7dfda',
    backgroundColor: '#fffdf8',
  },
  groupParticipantPillSelf: {
    backgroundColor: '#2f7254',
    borderColor: '#2f7254',
  },
  groupParticipantPillOnline: {
    backgroundColor: '#e8f5ee',
    borderColor: '#c4ded1',
  },
  groupParticipantPillOffline: {
    backgroundColor: '#f8e7df',
    borderColor: '#eccabc',
  },
  groupParticipantLabel: {
    color: '#2f7254',
    fontSize: 13,
    fontWeight: '700',
  },
  groupParticipantLabelSelf: {
    color: '#ffffff',
  },
  groupParticipantLabelOnline: {
    color: '#2f7254',
  },
  groupParticipantLabelOffline: {
    color: '#7b4630',
  },
  networkRow: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#fff',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  networkRowDisabled: {
    opacity: 0.55,
  },
  networkLeft: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  networkName: {
    color: '#2f7254',
    fontSize: 16,
    fontWeight: '700',
  },
  networkMeta: {
    color: '#61746a',
    fontSize: 13,
  },
  networkWarning: {
    color: '#8a5a00',
    fontSize: 12,
    lineHeight: 18,
  },
  networkTags: {
    alignItems: 'flex-end',
    gap: 6,
  },
  tag: {
    color: '#2f7254',
    backgroundColor: '#e8f5ee',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '700',
  },
  tagWarning: {
    color: '#8a5a00',
    backgroundColor: '#fff1cf',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '700',
  },
  tagMuted: {
    color: '#58655e',
    backgroundColor: '#eef1ef',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '700',
  },
  selectionCard: {
    backgroundColor: '#eef5ef',
    borderRadius: 20,
    padding: 16,
    gap: 10,
  },
  selectionLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    color: '#4f6b5e',
    fontWeight: '700',
  },
  selectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2f7254',
  },
  selectionCopy: {
    color: '#556860',
    fontSize: 14,
    lineHeight: 21,
  },
  statusText: {
    color: '#2f7254',
    fontSize: 14,
    lineHeight: 20,
  },
  linkText: {
    color: '#2f7254',
    fontWeight: '800',
    fontSize: 13,
  },
  linkTextDisabled: {
    color: '#6d7d74',
  },
  rowAction: {
    flexShrink: 0,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#e8f5ee',
    borderWidth: 1,
    borderColor: '#c4ded1',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 88,
  },
  rowActionDisabled: {
    backgroundColor: '#edf1ef',
    borderColor: '#d6dfd9',
  },
  networkSheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(8,22,16,0.32)',
    padding: 12,
  },
  networkSheetCard: {
    backgroundColor: '#fffdf8',
    borderRadius: 24,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: '#d6dfd9',
  },
  debugCard: {
    backgroundColor: '#f3f7f4',
    borderRadius: 18,
    padding: 14,
    gap: 10,
  },
  debugTitle: {
    color: '#2f7254',
    fontSize: 16,
    fontWeight: '800',
  },
  debugCopy: {
    color: '#5a6b62',
    fontSize: 13,
    lineHeight: 19,
  },
  debugRow: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#fff',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  webviewFrame: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#d6dfd9',
    backgroundColor: '#fff',
  },
  webview: {
    backgroundColor: '#fff',
  },
  successBox: {
    backgroundColor: '#e7f5ee',
    borderRadius: 18,
    padding: 16,
    gap: 8,
  },
  portalBox: {
    backgroundColor: '#fff8e6',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#f0d98a',
    padding: 16,
    gap: 10,
  },
  successTitle: {
    color: '#2f7254',
    fontSize: 20,
    fontWeight: '800',
  },
  successCopy: {
    color: '#2f7254',
    lineHeight: 21,
  },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#2f7254',
  },
  modalSurface: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f8f3e6',
    paddingTop: 18,
  },
  spaceCreatorSheet: {
    flex: 1,
    width: '100%',
    backgroundColor: '#fffdf7',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: '#d6dfd9',
    overflow: 'hidden',
  },
  spaceCreatorSheetContent: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    gap: 14,
  },
  spaceCreatorFooter: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: '#e3ebe5',
    backgroundColor: '#fffdf7',
  },
  scanner: {
    flex: 1,
  },
  scannerChrome: {
    padding: 20,
    gap: 10,
    backgroundColor: 'rgba(8,22,16,0.92)',
  },
  scannerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#f7f4ec',
  },
  scannerCopy: {
    color: '#d2ddd5',
    lineHeight: 21,
  },
});

